name: test

on:
  push:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Nginx configuration
        run: make test
